### PR TITLE
feat: FIR-28769: special treatment of 404 status when accessing account

### PR DESCRIPTION
**Pull request by alexradzin**

### CODE REVIEW

**Review by ptiurin — COMMENTED** [review]
Can we add an integration test for this? We can create an account with restrictive RBAC and another with correct RBAC but not linked to a user and use those in our tests.

**Comment by alexradzin** [comment]
> Can we add an integration test for this? We can create an account with restrictive RBAC and another with correct RBAC but not linked to a user and use those in our tests.

Do we have such tests in other drivers that have the same feature? Let's separate this: first create special account, then implement this test for each driver. BTW I even not sure that this feature is already supported at the server side.

**Comment by ptiurin** [comment]
> Do we have such tests in other drivers that have the same feature? Let's separate this: first create special account, then implement this test for each driver. BTW I even not sure that this feature is already supported at the server side.

We do, all our changes should contain the relevant tests as well. Let's keep the change and tests together in here as well.
A better strategy instead of having one persistent account was discussed on one of the dailies - a test account is created in the test itself, via the SQL and destroyed on the test completion.

**Comment by alexradzin** [comment]
Done

**Review by ptiurin — APPROVED** [review]

**Pull request merged**
